/**
 * The README's "data collected" table, generated from the `Features` schema (architecture 4.5):
 * every field the library can put in `features`, with its type and bounds taken from the schema
 * constants, so a new field cannot ship undocumented. test/readme.test.ts fails when the README
 * is out of date. Usage: pnpm --filter @agentlens/runners-ts data-table [--write]
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  COUNT_KEYS,
  COUNT_MAX,
  HIST_EDGES,
  MARKER_KEYS,
  MOMENT_CLAMP,
  PROBE_BOUNDS,
  RENDERERS,
  type CountKey,
  type HistKey,
  type Markers,
  type MomentKey,
  type Probes,
} from "../../../packages/core/src/features";

export const README = fileURLToPath(new URL("../../../README.md", import.meta.url));
export const START =
  "<!-- data-collected:start (generated by `pnpm --filter @agentlens/runners-ts data-table --write`) -->";
export const END = "<!-- data-collected:end -->";

const COUNTS: Record<CountKey, string> = {
  mouseEvents: "Trusted pointer events from a mouse",
  touchEvents: "Trusted pointer events from touch",
  penEvents: "Trusted pointer events from a pen",
  clicks: "Trusted primary-button mouse clicks (pointerdown then pointerup)",
  anchoredClicks: "Clicks whose start point is known (not the first on a page)",
  singleMoveClicks: "Clicks with at most one move in the 300 ms before",
  displacedSingleMoveClicks: "Single-move clicks that also jumped from the previous point",
  shortDwellClicks: "Clicks held under 20 ms",
  singleMoveShortDwellClicks: "Clicks both single-move and under 20 ms",
  mouseMoves: "Trusted mouse moves",
  mouseActiveSecs: "Seconds with any mouse activity",
  activations: "Trusted clicks with no pointer chain (keyboard, switch, screen reader)",
  untrustedClicks: "Script-dispatched clicks",
  orphanClicks: "Script-dispatched clicks with no pointerdown",
  centreSampled: "Of the first 12 mouse clicks, how many were measured against their target",
  centreHits: "Of those, how many landed within 5% of the target's centre",
  centreSizes: "Distinct target sizes among those clicks",
  hovered: "Elements hovered (the elements themselves are not kept)",
  hoveredClicked: "Hovered elements that were then clicked",
  idleGaps: "Gaps over 1 s between actions",
  idleMoves: "Mouse moves during those gaps",
  idleSecs: "Total seconds of those gaps",
  keys: "Trusted keydowns",
  chars: "Keydowns of the character class (the key itself is not kept)",
  imeKeys: "IME composition keydowns (keyCode 229)",
  repeatKeys: "Auto-repeat keydowns",
  navKeys: "Navigation keydowns (Tab, arrows, Page Up/Down, Home, End)",
  pasteKeys: "Paste shortcuts",
  findKeys: "Find shortcuts",
  inputs: "Input events in observed fields",
  untrustedInputs: "Script-dispatched input events",
  compositions: "IME compositions started",
  valueJumps: "Fields whose value grew by more than 3 characters with no keydown",
  fillFields: "Fields filled that way outside the human paths (dictation, autofill, paste)",
  keylessInsertText: "Trusted keyless insertText (dictation, Voice Control)",
  autofillJumps: "Value jumps in fields with an autocomplete hint",
  pastes: "Paste events (the clipboard is never read)",
  copies: "Copy events",
  contextmenus: "Context menus opened",
  pasteNoCopy: "Pastes with no copy or context menu first on the page",
  buTrio: "Browser Use's synthetic input, change and blur sequence",
  wheelTicks: "Wheel events",
  wheelGestures: "Wheel gestures (ticks separated by more than 300 ms)",
  wheelSameDelta: "Wheel ticks with the same delta as the previous tick",
  wheelFractional: "Wheel ticks with a fractional delta (a trackpad hint)",
  wheelSmall: "Wheel ticks under 4 px (a trackpad hint)",
  noInputScrolls: "Document scrolls with no wheel, touch or key input in the 500 ms before",
  scrollThenAct: "Such scrolls followed within 1 s by a click",
  hiddenTransitions: "Times the tab went hidden",
  hiddenInputs: "Trusted keydowns or pointerdowns at least 500 ms into a hidden period",
  actionGaps: "Gaps between consecutive actions",
  cadenceGaps: "Of those, gaps of 1.5 to 8 s",
  stillGaps: "Of those, gaps with at most one mouse move",
};

const HISTS: Record<HistKey, string> = {
  clickDwell: "Click hold time, ms",
  interKey: "Time between keydowns, ms (one bin is 10-15 ms)",
  keyHold: "Key hold time, ms",
  wheelDt: "Time between wheel ticks, ms",
  wheelDelta: "Wheel distance per tick, px",
  actionGap: "Time between actions, ms",
  centreDev: "Click distance from the target's centre, as a fraction of its size",
  clickSlip: "Pointer movement between pointerdown and pointerup, px",
};

const MOMENTS: Record<MomentKey, string> = {
  interKey: "Time between keydowns",
  wheelDt: "Time between wheel ticks",
  actionGap: "Time between actions",
};

const PROBES: Record<keyof Probes, string> = {
  webdriver: "`navigator.webdriver` is true",
  webdriverOwn: "`webdriver` is defined on the navigator object itself (a stealth patch)",
  headlessUA: "The user agent says HeadlessChrome",
  platformMismatch: "Client Hints platform disagrees with the user agent's OS (Chromium)",
  pointerMediaTell: "A desktop user agent without `(hover:hover)` and `(pointer:fine)`",
  renderer: "WebGL renderer, bucketed on the device; the raw string is never kept",
  outerEqInner: "Window outer size equals inner size",
  availEqScreen: "Available screen equals the full screen",
  xgaDpr1: "An XGA or WXGA screen at device pixel ratio 1",
  fwGlobals: "An automation framework global is present (Playwright, Selenium, ChromeDriver)",
  tzQuarterHours: "UTC offset in 15-minute steps",
  maxTouchPoints: "`navigator.maxTouchPoints`",
  anyCoarse: "`(any-pointer:coarse)` matches",
  pointerFine: "`(pointer:fine)` matches",
  desktopUA: "The user agent is a desktop one",
};

const MARKERS: Record<keyof Markers, string> = {
  claude: "A Claude in Chrome page marker was seen",
  browserUse: "A Browser Use or legacy Playwright highlight marker was seen",
  custom: "One of your `extraMarkers` was seen",
};

const MOMENT_FIELDS = "`{n, sum, sumSq}` or `null`";

export function dataTable(): string {
  const rows: string[][] = [];
  for (const k of COUNT_KEYS) rows.push([`counts.${k}`, `integer 0-${COUNT_MAX}`, COUNTS[k]]);
  for (const [k, edges] of Object.entries(HIST_EDGES) as [HistKey, readonly number[]][])
    rows.push([
      `hist.${k}`,
      `${edges.length + 1} integer bins (edges ${edges.join(", ")}) or \`null\``,
      HISTS[k],
    ]);
  for (const [k, clamp] of Object.entries(MOMENT_CLAMP) as [MomentKey, number][])
    rows.push([
      `moments.${k}`,
      `${MOMENT_FIELDS}, integer ms, each sample clamped to ${clamp}`,
      `Count, sum and sum of squares of ${MOMENTS[k].toLowerCase()}, for a variance`,
    ]);
  for (const [k, b] of Object.entries(PROBE_BOUNDS) as [
    keyof Probes,
    (typeof PROBE_BOUNDS)[keyof Probes],
  ][])
    rows.push([
      `probes.${k}`,
      b === "bool"
        ? "boolean or `null`"
        : b === "renderer"
          ? `one of ${RENDERERS.join(", ")}, or \`null\``
          : `integer ${b[0]} to ${b[1]} or \`null\``,
      PROBES[k],
    ]);
  for (const k of MARKER_KEYS) rows.push([`markers.${k}`, "boolean", MARKERS[k]]);
  const table = [
    "| Field | Type and bounds | What it is |",
    "| --- | --- | --- |",
    ...rows.map((r) => `| \`${r[0]}\` | ${r[1]} | ${r[2]} |`),
  ];
  return [START, "", ...table, "", END].join("\n");
}

/** Ignores table padding, which the formatter (oxfmt) adds after generation. */
export function normalise(md: string): string {
  return md
    .split("\n")
    .map((l) => l.replace(/-{3,}/g, "---").replace(/\s+/g, " ").trim())
    .join("\n");
}

/** The README with its generated section replaced; throws if the markers are missing. */
export function withTable(readme: string): string {
  const a = readme.indexOf(START);
  const b = readme.indexOf(END);
  if (a < 0 || b < a) throw new Error("README has no data-collected markers");
  return readme.slice(0, a) + dataTable() + readme.slice(b + END.length);
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) {
  const current = readFileSync(README, "utf8");
  const next = withTable(current);
  if (process.argv.includes("--write")) {
    writeFileSync(README, next);
    console.log(
      normalise(next) === normalise(current)
        ? "README already up to date"
        : "README table updated; run pnpm format",
    );
  } else {
    console.log(dataTable());
  }
}
